name: Quality Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Compose environment
        run:  docker compose -f docker-compose.development.yml up -d --build

  codestyle:
    name: Code Style
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run PHPCS (PHP CodeSniffer)
        run: docker compose -f docker-compose.development.yml exec -T app phpcs --standard=PSR12 src/

      - name: Run PHPMD (PHP Mess Detector)
        run: docker compose -f docker-compose.development.yml exec -T app phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: codestyle

    steps:
      - name: Stop and remove Docker containers
        run: docker-compose down
